
server.port: 5000

# Source database must be defined with environment variables
source_db: taxonomy
source_user: sa
source_server: ${SOURCE_SERVER}
source_pw: ${SOURCE_PW}

# WARNING: ALL TARGET TABLES WILL BE TRUNCATED BEFORE COPYING FROM SOURCE
target_db: taxonomy
target_user: sa
target_server: ${TARGET_SERVER}
target_pw: ${TARGET_PW}

dynamodb:
  server: ${QUEUE_SERVER}
  region: eu-central-1
  table-name: taxo

target-queue:
  host-url: ${SYNC_TARGET}
  wait-time-between-retries: 300000

---

spring:
  profiles: local

server.port: 5001

target-queue:
  wait-time-between-retries: 10000
  client-id: ${CLIENT_ID}
  client-secret: ${CLIENT_SECRET}
  token-server: ${TOKEN_SERVER}

dynamodb:
  table-name: taxonomy-sync-local

---

spring:
  profiles: dev

dynamodb:
  table-name: taxonomy-sync-dev

---

spring:
  profiles: test

dynamodb:
  table-name: taxonomy-sync-test

---