
server.port: 5001

# Source database must be defined with environment variables
source_db: ${SOURCE_DB}
source_user: ${SOURCE_USER}
source_server: ${SOURCE_SERVER}
source_pw: ${SOURCE_PW}

# WARNING: ALL TARGET TABLES WILL BE TRUNCATED BEFORE COPYING FROM SOURCE
target_db: ${TARGET_DB}
target_user: ${TARGET_USER}
target_server: ${TARGET_SERVER}
target_pw: ${TARGET_PW}

queue_server: ${QUEUE_SERVER}
queue_region: ${QUEUE_REGION}

requestqueue:
  enabled: false
  target-host: localhost:5000
  wait-time-between-retries: 300000